baseURL: https://ktrk115.github.io/
defaultContentLanguage: en
theme: nobineko
googleAnalytics: G-H6BFSWX4YM
timeout: 3000

languages:
  en:
    contentDir: content/en/
    languageName: English
    title: Kotaro Kikuchi
    weight: 1
  ja:
    contentDir: content/ja/
    languageName: Japanese
    title: 菊池 康太郎
    weight: 2

params:
  fontAwesomeKit: 1fe51c925c
  description: Kotaro Kikuchi's page
  lastUpdate: 2025-04-28

  profile:
    contact: kikuchi_kotaro_xa@cyberagent.co.jp

    link:
      - name: GitHub
        icon: fab fa-github
        url: https://github.com/ktrk115/

      - name: Twitter
        icon: fab fa-twitter
        url: https://twitter.com/ktrk115/

      - name: LinkedIn
        icon: fab fa-linkedin
        url: https://www.linkedin.com/in/ktrk115/

      - name: Google Scholar
        icon: fas fa-graduation-cap
        url: https://scholar.google.com/citations?user=hTqGOekAAAAJ

      - name: dblp
        url: https://dblp.uni-trier.de/pid/191/1049.html

      - name: cv
        url: https://drive.google.com/file/d/1QrwKB6L-4HxOGz6L2JYy4H_4aPuqfzBa/view?usp=sharing
